spring.application.name=FinalP3

# Configuración del servidor 
server.port=8081

# Habilitar DevTools para reinicio automático
spring.devtools.restart.enabled=true
spring.main.allow-bean-definition-overriding=true